% Cleaning up data from TDOA3 to input to fall_func
function [mag_table, loc_table, w_table, p_table] = TDOA3_Cleaner(data)
    data_1 = data(:,1);
    data_2 = data(:,2);
    data_3 = data(:,3);
    [data_1_peaks, data_1_locs, data_1_w, data_1_p] = TDOA3(data_1);
    [data_2_peaks, data_2_locs, data_2_w, data_2_p] = TDOA3(data_2);
    [data_3_peaks, data_3_locs, data_3_w, data_3_p] = TDOA3(data_3);
    T = zeros(size(data_3_peaks,1),12);         
    for sensor3_row = 1:size(data_3_peaks,1)
        peak_idx = data_3_locs(sensor3_row,1);
        for x = 1:size(data_1_peaks,1)             % go through sensor 2
            for y = 1:size(data_2_peaks,1)            % go thorugh sensor 3
                if abs(peak_idx - data_1_locs(x,1))<1000
                    if abs(peak_idx - data_2_locs(y,1)) <1000    % peaks match
                        T(sensor3_row, :) = [data_1_peaks(x,1),...
                                   data_1_locs(x,1),...
                                   data_1_w(x,1),...
                                   data_1_p(x,1),...
                                   data_2_peaks(y,1),...
                                   data_2_locs(y,1),...
                                   data_2_w(y,1),...
                                   data_2_p(y,1),...
                                   data_3_peaks(sensor3_row,1),...
                                   data_3_locs(sensor3_row,1),...
                                   data_3_w(sensor3_row,1),...
                                   data_3_p(sensor3_row,1)];
                    end
                end
            end
        end
    end
    sensor1_mag = T(:,1);
    sensor1_loc = T(:,2);
    sensor1_w = T(:,3);
    sensor1_p = T(:,4);
    sensor2_mag = T(:,5);
    sensor2_loc = T(:,6);
    sensor2_w = T(:,7);
    sensor2_p = T(:,8);
    sensor3_mag = T(:,9);
    sensor3_loc = T(:,10);
    sensor3_w = T(:,11);
    sensor3_p = T(:,12);
    mag_table = horzcat(sensor1_mag,...
                        sensor2_mag,...
                        sensor3_mag);
    loc_table = horzcat(sensor1_loc,...
                        sensor2_loc,...
                        sensor3_loc);
    w_table = horzcat(sensor1_w,...
                      sensor2_w,...
                      sensor3_w);
    p_table = horzcat(sensor1_p,...
                      sensor2_p,...
                      sensor3_p);
end